version: "3"
services:
  api-feed:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    container_name: nodejs-feed
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - /node_modules
      - ./:/app
    env_file:
      - ./.env